### ISSUE TITLE
Segmentation fault for prebuilt 2.1.0 on Ubuntu 18.04/19.10

### ISSUE THREAD

**Issue by z0rc** [rapid7/awsaml#126]
Downloaded archive from releases page, extracted, `chmod +x Awsaml`, `./Awsaml` to run, get:
```
% ./Awsaml       
[1]    12156 segmentation fault (core dumped)  ./Awsaml
```

**Comment by z0rc** [comment]
Same crash on Ubuntu 19.04.

Attaching `gdb` shows that segfault is in electron's bundled `libnode.so`.

I've run `yarn upgrade` to upgrade all modules, rebuilt with `yarn build` and `awsaml` launches fine after this.

I believe it's time for new point release with updated modules.

**Comment by asebastian-r7** [comment]
Alright, 2.2.1 is now out: https://github.com/rapid7/awsaml/releases/download/v2.2.1/awsaml-v2.2.1-linux-x64.zip. I have verified it works on 19.10. You will need to `apt-get install libgconf-2-4`, but that's it. The Awsaml binary works out of the box with that package installed. Thanks for reporting this!
