### ISSUE TITLE
Support Multiple profiles at the same time

### ISSUE THREAD

**Issue by vkomarov-r7** [rapid7/awsaml#149]
If possible, it would be really nice to be able to have AWSAML support refreshing more than one profile at once. Looking at the generated profile names, they are already unique as they have account ID within them. Ideally we could either select a set of accounts to keep temporary keys out for, or just do all of the ones configured in the tool.

Our specific usecase: Within Divvycloud we usually configure multiple AWS accounts to be tracked, and it would be nice to be able to configure those accounts using the emitted profile strings generated by the tool.

**Comment by az-kennedy** [comment]
How does one go about doing this?
