### ISSUE TITLE
Provide contributing guidelines for Awsaml

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/awsaml#20]
So people can be confident their changes will be accepted into Awsaml, we should provide [contributor guidelines](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) in the form of a CONTRIBUTING.md document at the root of the repository. This document should include
- instructions on formatting commit messages in code
- guidelines for scoping changes within a pull request
- instructions on formatting pull requests (see #22)
- links to the documentation for testing (see #18)
- links to the documentation for releases (see #21)

**Comment by erran-r7** [comment]
:heart_eyes:
