### ISSUE TITLE
Design a RESTful interface for Awsaml

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/awsaml#24]
A RESTful interface for Awsaml should take the following things into consideration
- versioning through a named URL e.g. `/v1/...`
- support for retrieving individual id, key, and token values
- support for [retrieving EC2 instance metadata style security credentials](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials)
- support for Awsaml managing multiple AWS accounts simultaneously

The resulting design should be documented in a [Markdown](https://daringfireball.net/projects/markdown/) formatted file name "docs/restful-api.md".

**Comment by dabdine-r7** [comment]
I'm proposing a new workflow and a set of features to support that workflow from what awsaml does today. I've already tested this workflow with a prototype I've written a while ago and it seemed to fit my use cases well.

The use case statement is:

The core of the use case is that I need awsaml to manage multiple accounts. I would like it to keep AWS access keys to those accounts updated as long as I ask it to. I would like awsaml to keep multiple accounts up to date simultaneously so I can switch between them rapidly if I need to.

Here's my proposed workflow:
1. A user runs awsaml. Awsaml appears in the system tray with an icon (mac, windows -- perhaps kubuntu for linux, etc.).
2. A user can configure one ore more SAML metadata URLs. The user can supply the name of the account related to that SAML URL.
3. Each configured account appears in a drop down under the system tray icon.
4. A user can select one or more accounts for awsaml to keep up to date. Awsaml opens up the saml authentication window to prompt the user to authenticate once a user has enabled awsaml management of that account. Accounts that are enabled in the drop-down appear with a check box to the left of their name.

**Comment by dgreene-r7** [comment]
Resolved in https://github.com/rapid7/awsaml/pull/114.
