### ISSUE TITLE
Project: Iconic Identity

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/awsaml#25]
Awsaml currently uses the stock Electron icon. To provide better visual distinction between it and other Electron applications, Awsaml should have its own icon. We need several icon file formats to account for all the OSes we support. Plus, the build process needs updated to package the icon.

Issues related to this project are filed under the "[iconic-identity](https://github.com/rapid7/awsaml/milestones/iconic-identity)" milestone.

**Comment by dgreene-r7** [comment]
Fixed in #217
