### ISSUE TITLE
Update Awsaml's build process to inject icons

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/awsaml#26]
Awsaml's build process uses [electron-packager](https://github.com/electron-userland/electron-packager) for packaging. We should be able to add the `--icon` flag to the build process to create a custom application icon. For now, we can leverage the [stock Electron
icons](https://github.com/atom/electron/blob/master/atom/browser/resources) and update the build process to inject those. Once we have OS specific icons (see #28, #29, and #30), the build process will pick them up. Icons should go in a "resources" folder in the root of the project.

**Comment by dgreene-r7** [comment]
Fixed in #217
