### ISSUE TITLE
Add a "Recent Logins" list to the configuration page

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/awsaml#49]
To facilitate account switching, users need a way to log out (see #48) and a way to log back in. The current "remember the last metadata URL used" method isn't sufficient for handling multiple accounts. We should add a "Recent Logins" list to the configuration page. The list should be of the last six URLs successfully used to login.

If a URL in the "SAML Metadata URL" box is already in the list, the existing URL in the list should be moved to the top and the list length shouldn't change. If a URL in the box isn't already in the list, the URL should be added to the top of the list and the list truncated to the last six used URLs.

URLs should be ordered on the configuration page with the most recently used URL at the top of the list. URLs in the list should be selectable and copyable so that users can cut and paste them into the "SAML Metadata URL" box.

The maximum length of the list should be stored as a [configuration parameter](https://github.com/rapid7/awsaml/blob/0a4275ba59dc48d64eed9d614ce9362444af5fce/config.json).

**Comment by rhodgman-r7** [comment]
This would be a great feature to have. You might even consider enhancing this:

> URLs should be ordered on the configuration page with the most recently used URL
> at the top of the list. URLs in the list should be selectable and copyable so that
> users can cut and paste them into the "SAML Metadata URL" box.

by putting a button next to each of the recent urls which would allow the user to click that button and initiate the login sequence instead of having to copy and paste the url.

**Comment by erran-r7** [comment]
@asharma-r7 this is the issue I mentioned that we'd love some UI ✨ magic on. 😉

**Comment by rhodgman-r7** [comment]
I'm psyched that you're working on this, I switch accounts pretty frequently and this will make things easier. Thank you.

**Comment by erran-r7** [comment]
@rhodgman-r7 👍 I'm excited. Currently I've implemented the copy step. Eventually we may make the button a "log into existing provider" button instead.
