### ISSUE TITLE
White-space characters in the copy-pasta box break some shells

### ISSUE THREAD

**Issue by jmanero-r7** [rapid7/awsaml#64]
The code-box with generated `export` ENVAR commands has some trailing white-space characters that break Bash due to slight variations in OS's clipboard semantics AFAIK. On OS X, copy-pasting both lines works as expected. However, on an Ubuntu/Unity desktop, I've observed this breaking the boto/python based aws-cli. Copy-pasting each line individually, being careful not to select past the last printable-character, fixes the issue.

**Comment by erran-r7** [comment]
@jmanero-r7 in #78 I use `clipboard.js` for selections. We could likely use it to add a copy button on that page as well. @rfennell-r7 pointed this out over my shoulder as well as seeing this issue in the backlog.
