### ISSUE TITLE
Make profile name configurable

### ISSUE THREAD

**Issue by athompson-r7** [rapid7/awsaml#65]
We are currently using `awsaml-${session.accountId}` as the profile in `$HOME/.aws/credentials`.

If you are dealing with many AWS accounts or if the accounts you are dealing with have very similar account ids it can become confusing.

This should include changing the call to [`AwsCredentials.save`](https://github.com/rapid7/awsaml/blob/17e8cb3cb50ecbf437c8a48d44e4814f78d8df0d/lib/routes/refresh.js#L41) and updating the [refresh view](https://github.com/rapid7/awsaml/blob/9de4d254ffdca31f077bb717d41ddc12d1a8d523/views/refresh.jsx#L64-L65).

**Comment by fmitchell-r7** [comment]
This was added in [PR #94](https://github.com/rapid7/awsaml/pull/94) and shipped in the [v1.5.0](https://github.com/rapid7/awsaml/releases/tag/v1.5.0) release.
