### ISSUE TITLE
Make potentially sensitive information hidden by default

### ISSUE THREAD

**Issue by rhodgman-r7** [rapid7/awsaml#66]
When I start an awsaml session I get a window that looks like the following:

![screen shot 2016-06-30 at 2 18 22 pm](https://cloud.githubusercontent.com/assets/4821087/16499390/4b139f4e-3ece-11e6-9740-8d2c3fad0d1a.png)

Not that this is a very likely attack vector, but with that window up, someone could capture the information in that window (with a camera? a really good memory?) and then transfer it to another device and use AWS services impersonating me.

Since awsml conveniently writes that data to ~/.aws/credentials already, it also seems unlikely that anyone would really need to copy and paste it from the awsaml GUI to somewhere else.

So, would you consider a modification in which the access key, secret key and session token info is hidden by default in the awsaml GUI, but could be revealed after clicking on a button?

**Comment by erran-r7** [comment]
@rhodgman-r7 check out #73.

**Comment by erran-r7** [comment]
@rhodgman-r7 shipped with #73. I'll try to remember to comment here again once it has gone out in a release. 👍

**Comment by rhodgman-r7** [comment]
@erran-r7 I just saw this now, it looks good. Thanks for doing this.

**Comment by erran-r7** [comment]
@rhodgman-r7 no problem. Was cool to see people outside of our core maintainers contributing back to (vs. just using) the project my reporting issues. 😄
