### ISSUE TITLE
Allow targeted builds for various platforms

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/awsaml#86]
Version 1.4.0 of Awsaml hard codes Mac, Linux, and Windows as the [build platforms](https://github.com/rapid7/awsaml/blob/v1.4.0/package.json#L19) when running `npm run build`. We should allow that to be set via an environment variable.
```bash
export PLATFORM=darwin
npm run build
```
This will make it easier to target specific builds on specific build machines.

**Comment by athompson-r7** [comment]
@fmitchell-r7 Should there be a default to retain the existing behavior?

**Comment by fmitchell-r7** [comment]
@athompson-r7, yes. We'll need to do something like
```
PLATFORM=${PLATFORM:=darwin,linux,win32}
```
so to keep the existing behavior of building for all three platforms.
