### ISSUE TITLE
Allow user to add nickname to metadata url optionally

### ISSUE THREAD

**Issue by vchaudhari-r7** [rapid7/awsaml#91]
It would be super handy if we can attach human readable label to metadata url. This will allow us to use 'Recent Logins' easily without having to lookup account number and figure to what account is it.

From design perspective, we can add optional text field box under text box 'SAML Metadata URL' and capture the input and append to recent login labels. for e.g.

Recent Logins
--------------------------------------------------------------------------------------------
|awsaml-XXXXXXXXXXX ( POKEMON-Prod )
|>` https://<metadata-url>/metadata`

**Comment by fmitchell-r7** [comment]
I can see this relating to #65, which is about allowing profile names be configurable. Right now, metadata URLs are saved as [a map from URL to profile name](https://github.com/rapid7/awsaml/blob/0caa82e70fea5623ad479dcc6ea204aac37f43c5/lib/routes/refresh.js#L44-L48).

**Comment by udangel-r7** [comment]
#94 should provide that

**Comment by fmitchell-r7** [comment]
This was added in [PR #94](https://github.com/rapid7/awsaml/pull/94) and shipped in the [v1.5.0](https://github.com/rapid7/awsaml/releases/tag/v1.5.0) release.
